
$hypr = ~/.config/hypr/hyprland

source = $hypr/workspaces.conf
source = $hypr/autostart.conf
source = $hypr/env.conf
source = $hypr/keybinds.conf
source = $hypr/animations.conf
source = $hypr/decor.conf
source = $hypr/rules.conf
