exec-once = waybar
exec-once = hypridle
exec-once = swww-daemon
exec-once = systemctl --user start hyprpolkitagent

# exec-once = ivpn
exec-once = steam
exec-once = spotify
exec-once = vesktop
exec-once = flebop
exec-once = $HOME/soldots/dots/hypr/scripts/noisetorch-autostart
