input {
    kb_layout = gb
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
}

# device {
#     name = logitech-usb-receiver
#     accel_profile = flat
#     sensitivity = -0.2
# }

device {
    name = logitech-g303-1
    accel_profile = flat
    sensitivity = -0.2
}

